name: Build Tweaks (Helper)

on:
  workflow_call:
    inputs:
      enable_youpip:
        type: boolean
        required: true
        default: false

      enable_ytuhd:
        type: boolean
        required: true
        default: false

      enable_yq:
        type: boolean
        required: true
        default: false

      enable_ryd:
        type: boolean
        required: true
        default: false

      enable_ytabc:
        type: boolean
        required: true
        default: false

      enable_demc:
        type: boolean
        required: true
        default: false

      enable_ytweaks:
        type: boolean
        required: true
        default: false

      enable_gonerino:
        type: boolean
        required: true
        default: false

      enable_youspeed:
        type: boolean
        required: true
        default: false

      enable_YTLCM:
        type: boolean
        required: true
        default: false

      enable_VolumeBoostYT:
        type: boolean
        required: true
        default: false

      enable_YouGetCaption:
        type: boolean
        required: true
        default: false

      enable_ytpf:
        type: boolean
        required: true
        default: false

      enable_ytpfBETA:
        type: boolean
        required: true
        default: false

      enable_ycq:
        type: boolean
        required: true
        default: false

      enable_ys:
        type: boolean
        required: true
        default: false

      enable_youloop:
        type: boolean
        required: true
        default: false

      enable_youmute:
       type: boolean
       required: true
       default: false

      tweak_version:
        type: string
        required: false
        default: ""

      tweak_url:
        type: string
        required: false
        default: ""

jobs:
  build-tweaks:
    name: Build Tweaks
    runs-on: macos-latest

    steps:
      - name: Check for conflicting inputs
        run: |
          if [[ "${{ inputs.enable_ytpf }}" == "true" && "${{ inputs.enable_ytpfBETA }}" == "true" ]]; then
            echo "::error::You can't select both inputs 'Integrate YTPlaybackFix' and 'Integrate YTPlaybackFix beta' at the same time. Please select only one of them."
            exit 1
          fi
          
      - name: Install Dependencies
        run: brew install make ldid dpkg

      - name: Set PATH environment variable
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Cache Theos
        if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc || inputs.enable_ytweaks || inputs.enable_gonerino || inputs.enable_youspeed || inputs.enable_YTLCM || inputs.enable_VolumeBoostYT || inputs.enable_YouGetCaption || inputs.enable_ytpf || inputs.enable_ytpfBETA || inputs.enable_ycq || inputs.enable_ys || inputs.enable_youloop || inputs.enable_youmute }}
        id: theos
        uses: actions/cache@v5
        env:
          cache-name: theos_cache_9bc7340
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: ${{ (inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc || inputs.enable_ytweaks || inputs.enable_gonerino || inputs.enable_youspeed || inputs.enable_YTLCM || inputs.enable_VolumeBoostYT || inputs.enable_YouGetCaption || inputs.enable_ytpf || inputs.enable_ytpfBETA || inputs.enable_ycq || inputs.enable_ys || inputs.enable_youloop || inputs.enable_youmute) && steps.theos.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v6
        with:
          repository: theos/theos
          ref: 9bc73406cf80b711ef4d02c15ff1dedc4478a275
          path: theos
          submodules: recursive

      - name: Download iOS SDK
        if: ${{ (inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc || inputs.enable_ytweaks || inputs.enable_gonerino || inputs.enable_youspeed || inputs.enable_YTLCM || inputs.enable_VolumeBoostYT || inputs.enable_YouGetCaption || inputs.enable_ytpf || inputs.enable_ytpfBETA || inputs.enable_ycq || inputs.enable_ys || inputs.enable_youloop || inputs.enable_youmute) && steps.theos.outputs.cache-hit != 'true' }}
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Download YouTube Plus (by ver)
        if: ${{ inputs.tweak_version != '' }}
        run: |
          deb_url="https://github.com/Mark02-2012/YTPlusM/releases/download/YTPlusVersions/com.dvntm.ytlite_${{ inputs.tweak_version }}_iphoneos-arm.deb"
          wget "$deb_url" --no-verbose -O ytplus.deb

      - name: Download YouTube Plus (by URL)
        if: ${{ inputs.tweak_url != '' }}
        run: |
          wget "${{ inputs.tweak_url }}" --no-verbose -O ytplus.deb
          file_type=$(file --mime-type -b ytplus.deb)
          if [[ "$file_type" != "application/vnd.debian.binary-package" ]]; then
            echo "::error::Validation failed: The file is not a valid DEB file. Detected type: $file_type."
            exit 1
          fi

      - name: Clone YouTubeHeader
        if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc || inputs.enable_ytweaks || inputs.enable_gonerino || inputs.enable_youspeed || inputs.enable_YTLCM || inputs.enable_VolumeBoostYT || inputs.enable_YouGetCaption || inputs.enable_ytpf || inputs.enable_ytpfBETA || inputs.enable_ycq || inputs.enable_ys || inputs.enable_youloop || inputs.enable_youmute }}
        run: |
          if [ -d "$THEOS/include/YouTubeHeader" ]; then
            cd $THEOS/include/YouTubeHeader && git pull
          else
            cd $THEOS/include && git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git
          fi
          if [ "${{ inputs.enable_demc }}" = "true" ]; then
            rm -rf "$THEOS/include/YTHeaders"
            cp -r "$THEOS/include/YouTubeHeader" "$THEOS/include/YTHeaders"
          fi

      - name: Clone PSHeader
        if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc || inputs.enable_ytweaks || inputs.enable_gonerino || inputs.enable_youspeed || inputs.enable_YTLCM || inputs.enable_VolumeBoostYT || inputs.enable_YouGetCaption || inputs.enable_ytpf || inputs.enable_ytpfBETA || inputs.enable_ycq || inputs.enable_ys || inputs.enable_youloop || inputs.enable_youmute }}
        run: |
          if [ -d "$THEOS/include/PSHeader" ]; then
            cd $THEOS/include/PSHeader && git pull
          else
            cd $THEOS/include && git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git
          fi

      - name: Clone YouPiP
        if: ${{ inputs.enable_youpip }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouPiP.git

      - name: Clone YTUHD
        if: ${{ inputs.enable_ytuhd }}
        run: git clone --quiet --depth=1 https://github.com/Tonwalter888/YTUHD.git

      - name: Clone Return-YouTube-Dislikes
        if: ${{ inputs.enable_ryd }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Dislikes.git

      - name: Clone YTABConfig
        if: ${{ inputs.enable_ytabc }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YTABConfig.git

      - name: Clone YouGroupSettings
        if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc || inputs.enable_ytweaks || inputs.enable_gonerino || inputs.enable_youspeed || inputs.enable_YTLCM || inputs.enable_VolumeBoostYT || inputs.enable_ytpf || inputs.enable_ytpfBETA }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouGroupSettings.git

      - name: Clone YouQuality
        if: ${{ inputs.enable_yq }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouQuality.git

      - name: Clone YTVideoOverlay
        if: ${{ inputs.enable_yq || inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_youspeed || inputs.enable_YouGetCaption || inputs.enable_ys || inputs.enable_youloop || inputs.enable_youmute }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YTVideoOverlay.git

      - name: Clone DontEatMyContent
        if: ${{ inputs.enable_demc }}
        run: git clone --quiet --depth=1 https://github.com/therealFoxster/DontEatMyContent.git

      - name: Clone YTweaks
        if: ${{ inputs.enable_ytweaks }}
        run: git clone --quiet --depth=1 https://github.com/fosterbarnes/YTweaks.git

      - name: Clone Gonerino
        if: ${{ inputs.enable_gonerino }}
        run: git clone --quiet --depth=1 https://github.com/castdrian/Gonerino.git
      
      - name: Clone YouSpeed
        if: ${{ inputs.enable_youspeed }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouSpeed.git

      - name: Clone YTLowContrastMode
        if: ${{ inputs.enable_YTLCM }}
        run: git clone --quiet --depth=1 https://github.com/Mark02-2012/YTLowContrastMode.git

      - name: Clone VolumeBoostYT
        if: ${{ inputs.enable_VolumeBoostYT }}
        run: git clone --quiet --depth=1 https://github.com/irum0320/VolumeBoostYT.git

      - name: Clone YouGetCaption
        if: ${{ inputs.enable_YouGetCaption }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouGetCaption.git

      - name: Clone YTPlaybackFix
        if: ${{ inputs.enable_ytpf }}
        run: git clone --quiet --depth=1 https://github.com/Mark02-2012/YTPlaybackFix.git

      - name: Clone YTPlaybackFix beta branch
        if: ${{ inputs.enable_ytpfBETA }}
        run: git clone --quiet --depth=1 -b beta-testing https://github.com/Mark02-2012/YTPlaybackFix.git

      - name: Clone YouChooseQuality
        if: ${{ inputs.enable_ycq }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouChooseQuality.git

      - name: Clone YouShare
        if: ${{ inputs.enable_ys }}
        run: git clone --quiet --depth=1 https://github.com/Tonwalter888/YouShare.git

      - name: Clone YouLoop
        if: ${{ inputs.enable_youloop }}
        run: git clone --quiet --depth=1 https://github.com/bhackel/YouLoop.git

      - name: Clone YouMute
        if: ${{ inputs.enable_youloop }}
        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouMute.git

      - name: Build YouPiP
        if: ${{ inputs.enable_youpip }}
        run: |
          cd YouPiP && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../youpip.deb

      - name: Build YTUHD
        if: ${{ inputs.enable_ytuhd }}
        run: |
          cd YTUHD && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../ytuhd.deb

      - name: Build Return-YouTube-Dislikes
        if: ${{ inputs.enable_ryd }}
        run: |
          cd Return-YouTube-Dislikes && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../ryd.deb

      - name: Build YTABConfig
        if: ${{ inputs.enable_ytabc }}
        run: |
          cd YTABConfig && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../ytabc.deb

      - name: Build YouGroupSettings
        if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc || inputs.enable_YTLCM || inputs.enable_VolumeBoostYT || inputs.enable_ytpf || inputs.enable_ytpfBETA }}
        run: |
          cd YouGroupSettings && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../ygs.deb

      - name: Build YouQuality
        if: ${{ inputs.enable_yq }}
        run: |
          cd YouQuality && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../yq.deb

      - name: Build YTVideoOverlay
        if: ${{ inputs.enable_yq || inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_youspeed || inputs.enable_YouGetCaption }}
        run: |
          cd YTVideoOverlay && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../ytvo.deb

      - name: Build DontEatMyContent
        if: ${{ inputs.enable_demc }}
        run: |
          cd DontEatMyContent && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../demc.deb

      - name: Build YTweaks
        if: ${{ inputs.enable_ytweaks }}
        run: |
          cd YTweaks && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../ytweaks.deb

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
         go-version: 'stable'

      - name: Build Gonerino
        if: ${{ inputs.enable_gonerino }}
        run: |
          cd Gonerino && gmake package FINALPACKAGE=1
          mv packages/*.deb ../gonerino.deb
          
      - name: Build YouSpeed
        if: ${{ inputs.enable_youspeed }}
        run: |
          cd YouSpeed && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../youspeed.deb

      - name: Build YTLowContrastMode
        if: ${{ inputs.enable_YTLCM }}
        run: |
          cd YTLowContrastMode && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../ytlcm.deb

      - name: Build VolumeBoostYT
        if: ${{ inputs.enable_VolumeBoostYT }}
        run: |
          cd VolumeBoostYT && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../volumeboostyt.deb
          
      - name: Build YouGetCaption
        if: ${{ inputs.enable_YouGetCaption }}
        run: |
          cd YouGetCaption && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../yougetcaption.deb

      - name: Build YTPlaybackfix
        if: ${{ inputs.enable_ytpf }}
        run: |
          cd YTPlaybackFix && make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ../ytpf.deb

      - name: Build YTPlaybackfix beta
        if: ${{ inputs.enable_ytpfBETA }}
        run: |
          cd YTPlaybackFix && make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ../ytpfbeta.deb

      - name: Build YouChooseQuality
        if: ${{ inputs.enable_ycq }}
        run: |
          cd YouChooseQuality && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../youchoosequality.deb

      - name: Build YouShare
        if: ${{ inputs.enable_ys }}
        run: |
          cd YouShare && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../youshare.deb

      - name: Build YouLoop
        if: ${{ inputs.enable_youloop }}
        run: |
          cd YouLoop && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../youloop.deb

      - name: Build YouMute
        if: ${{ inputs.enable_youmute }}
        run: |
          cd YouMute && make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ../youmute.deb

      - name: Clone Open in YouTube (Safari extension)
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/BillyCurtis/OpenYouTubeSafariExtension
          cd OpenYoutubeSafariExtension
          git sparse-checkout set --no-cone OpenYoutubeSafariExtension.appex
          git checkout
          mv *.appex ..

      - name: Upload built debs as artifacts
        uses: actions/upload-artifact@v7
        with:
          name: built-debs
          path: |
            *.deb
            *.appex
          if-no-files-found: ignore
          retention-days: 1
